### ISSUE TITLE
获取本子一部分图片后提示下载失败

### ISSUE THREAD

**Issue by mitian233** [lolishinshi/exloli#156]
这是因为账号被风控了吗，有什么方法解决？
![_20220112_131120.JPG](https://user-images.githubusercontent.com/13678847/149067681-16aeb2da-f97d-4bcb-ad6d-16e974fc8058.JPG)

**Comment by Aloxaf** [comment]
telegraph 有针对 IP 的上传频率限制

**Comment by mitian233** [comment]
等了半小时恢复正常了，原来不是eh的问题，感谢
